const data = [
  {
    _id: "product-1",
    title: "t-shirts",
    catagory: "tops",
    image: "../public/images/tshirt.jpg",
    price: 25.99,
    stock: 8,
    minium: 1,
  },
  {
    _id: "product-2",
    title: "pants",
    catagory: "bottoms",
    image: "../public/images/pants.jpg",
    price: 67.99,
    stock: 5,
    minium: 1,
  },
  {
    _id: "product-3",
    title: "sweater",
    catagory: "tops",
    image: "../public/images/sweater.jpg",
    price: 74.99,
    stock: 5,
    minium: 1,
  },
  {
    _id: "product-4",
    title: "beanies",
    catagory: "hats",
    image: "../public/images/beanie.jpg",
    price: 27.99,
    stock: 10,
    minium: 1,
  },
  {
    _id: "product-5",
    title: "shoes",
    catagory: "footware",
    image: "../public/images/shoes.jpg",
    price: 119.99,
    stock: 7,
    minium: 1,
  },
  {
    _id: "product-6",
    title: "flannel",
    catagory: "tops",
    image: "../public/images/flannel.jpg",
    price: 54.99,
    stock: 3,
    minium: 1,
  },
  {
    _id: "product-7",
    title: "glasses",
    catagory: "accessories",
    image: "../public/images/glasses.jpg",
    price: 79.99,
    stock: 3,
    minium: 1,
  },
];
